# Generated by Django 5.2.14 on 2026-05-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('tipoarquivo', models.CharField(max_length=1000)),
                ('dataUpload', models.DateField()),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
            },
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Policial',
                'verbose_name_plural': 'Policiais',
            },
        ),
        migrations.CreateModel(
            name='RelatorioEstatistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('infracao_mais_comum', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'RelatorioEstatistico',
                'verbose_name_plural': 'RelatoriosEstatisticos',
            },
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Rua',
                'verbose_name_plural': 'Ruas',
            },
        ),
        migrations.CreateModel(
            name='TipoInfracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gravidade', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'tipoInfracao',
                'verbose_name_plural': 'tipoInfracoes',
            },
        ),
        migrations.CreateModel(
            name='VeiculoConfiscado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('dono', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('data_de_confiscamento', models.DateField()),
                ('tem_documento', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'VeiculoConfiscado',
                'verbose_name_plural': 'VeiculosConfiscados',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('infrator', models.CharField(max_length=100)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evidencia')),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rua')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
            },
        ),
        migrations.CreateModel(
            name='Penalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_infrator', models.CharField(max_length=2)),
                ('responsavel', models.CharField(max_length=50)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policial')),
                ('tipo_infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoinfracao')),
            ],
            options={
                'verbose_name': 'Penalidade',
                'verbose_name_plural': 'Penalidades',
            },
        ),
        migrations.CreateModel(
            name='Investigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policial')),
            ],
            options={
                'verbose_name': 'Investigacao',
                'verbose_name_plural': 'Investigacoes',
            },
        ),
        migrations.CreateModel(
            name='ResultadoInvestigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.denuncia')),
                ('penalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penalidade')),
            ],
            options={
                'verbose_name': 'ResultadoInvestigacao',
                'verbose_name_plural': 'ResultadosInvestigacao',
            },
        ),
        migrations.CreateModel(
            name='RelatorioPorRua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('investigacoes_concluidas', models.CharField(max_length=100)),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rua')),
            ],
            options={
                'verbose_name': 'RelatorioPorRua',
                'verbose_name_plural': 'RelatoriosPorRua',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('n_casa', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rua')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='penalidade',
            name='infrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100000)),
                ('culpado', models.CharField(max_length=100000)),
                ('cidadão', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
