# Generated by Django 5.2.14 on 2026-06-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
